<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accessability Statment' => 'הצהרת נגישות',
    'Are you sure you want to delete this item?' => 'האם אתה בטוח שברצונך למחוק את הפריט הזה?',
    'Button Color' => 'צבע כפתורים',
    'Campain' => 'קמפיין',
    'Campains' => 'קמפיינים',
    'Create Campain' => 'צור קמפיין',
    'Delete' => 'מחק',
    'End Date' => 'תאריך סיום',
    'ID' => 'מזהה',
    'Image' => 'תמונה',
    'Logo' => 'לוגו',
    'Name' => 'שם מלא',
    'Freind Name' => 'שם החבר עליו אני ממליץ',
    'My Name' => 'שם הממליץ',
    'My Employee Number' => 'מספר עובד',
    'Save' => 'שמור',
    'Show Cv' => 'הצג קו"ח',
    'Show Licanse' => 'הצג רשיון',
    'Sid' => 'מזהה ספק',
    'Start Date' => 'תאריך התחלה',
    'The requested page does not exist.' => 'הדף המבוקש לא קיים',
    'Update' => 'עדכן',
    'Update Campain: {name}' => 'עדכן קמפיין: {name}',
    'Yes' => 'כן',
    'No' => 'לא',
    'Phone' => 'טלפון נייד',
    'Licanse' => 'בעל רשיון נהיגה לאוטובוס?',
    'Search Area' => 'משרה מבוקשת',
    'The above error occurred while the Web server was processing your request.' => 'השגיאה למעלה התרחשה בזמן ביצוע הבקשה',
    'Please contact us if you think this is a server error. Thank you.' => 'צור עימנו קשר במידה ואתה חושב שזו שגיאת שרת, תודה',
    'Not Found (#404)' => 'לא נמצא (#404)',
    'Forbidden (#403)' => 'לא מורשה (#403)',
    'Bad Request (#400)' => 'בקשה שגויה (#400)',
    'A campaign with this ID could not be found' => 'לא ניתן למצוא קמפיין עם המזהה שהוזן',
    'Thank you for your request! we will contact you soon' => 'תודה על פנייתך! ניצור איתך קשר בהקדם.',
    'Job Application - Egged' => 'אגד - הגשת מועמדות למשרה',
    'Attach CV file (Not Mandatory)' => 'צרף קובץ קורות חיים (לא חובה)',
    'Please fill out the following fields to login:' => 'מלא בבקשה את פרטים כדי להיכנס:',
    'Username' => 'שם משתמש',
    'Password' => 'סיסמה',
    'Login' => 'כניסה',
    'Egged Campaigns' => 'אגד - קמפיינים',
    'Jerusalem' => 'ירושלים',
    'Center' => 'מרכז',
    'South' => 'זכרון יעקב עד אילת',
    'North' => 'צפון',
    'East' => 'מזרח',
    'Send' => 'שלח >>',
    'More Jobs' => 'משרות נוספות',
    'Or call *2600 Ext. 4' => 'או התקשר 2800* שלוחה 4',
    'Supplier Id' => 'מזהה ספק',
    'Friend Brings Friend' => 'חבר מביא חבר',
    'Another Freind' => 'חבר נוסף',
    'New request - Egged Jobs' => 'בקשה חדשה - אגד משרות',
    'Show Campaign' => 'עבור והצג את דף הקמפיין',
    'Experiance' => 'השכלה',
    'Education' => 'ניסיון',
    'Accessibility' => 'הנגשה',
    'Contrast' => 'ניגודיות',
    'Increase Font' => 'הגדל טקסט',
    'Decrease Font' => 'הקטן טקסט',
    'Contact Text' => 'טקסט יצירת קשר',
    'We could not send your application. Please try later.' => 'התרחשה שגיאה בשליחת הפרטים.',
];
